#!/usr/bin/env bash

# install Python modules
pip install -r requirements.txt

# store modules in archive
cd lib/*/site-packages
zip ../../../dist/sigma-api \
	--filesync              \
	--quiet                 \
	--recurse-paths         \
	*
